### ISSUE TITLE
no ssh

### ISSUE THREAD

**Issue by pickeld** [mcchas/g2h-camera-mods#1]
Hey, first of i want to thank you for your hard work. you did incredible job!
i was copy hostname to the sdcard root folder. 
its seems like the camera does not listen on port 22 for SSH at all.

any suggestions?

**Comment by pickeld** [comment]
telnet is open. sorry

**Comment by mcchas** [comment]
Glad this is working for you! You could build dropbear with the right toolchain. Although there is not much free disk space as only half of the 32Mb flash is usable. These hacks just modify the existing firmware and telnet is all I needed.

**Comment by pickeld** [comment]
telnet is more than enough! thank you.
is it possible to add timestamp and / or change the stream resolution?
