### ISSUE TITLE
Available commands

### ISSUE THREAD

**Issue by fluppie** [mcchas/g2h-camera-mods#12]
By browsing the folders I found these commands:

# cd /local/bin
# ls
sdk_test_search       get_lumi_info         set_led_r             get_sn                iperf_client
get_zig_chipid        zig_permit_join_pre   set_led_b             wpa_cli               sdk_test_liveview
rtwpriv               get_model             zig_set_pa            set_homekit_info      debuger
hotplug               factory_test          zig_get_pa            get_homekit_info      zig_leave_all_device
iwspy                 monitor               set_product_info      avahi-autoipd         get_dev_status
zigbee_lqi            iwlist                get_product_info      key_test              set_language
qrcode                ota_checker           sdk_test_func         key_state             get_language
audio_test            modify_bootargs       homekit_ntp           mfi_test              sdk_test_audio
sdcard_test           get_soft_ver          sdk_test_playback     led_test              restore
iperf_server          ifrename              speaker               set_lens              hostapd
iwconfig              wpa_supplicant        wifi_rssi             get_lens              zig_permit_join
zig_leave_device      sdk_test_param        wifi_test             fac_console           iwpriv
asetprop              iwgetid               set_hd_ver            property_service      iperf
agetprop              get_zig_ver           get_hd_ver            uboot_tools           mic
set_lumi_info         get_zig_mac           set_sn                iwevent

Especially the set_language was handy to put it in English.

"get_language" to read the current lang and "set_language en" to put it in English

**Comment by mcchas** [comment]
Good find, sounds easier than doing the symlinks. Please submit a PR with your findings 👍

**Comment by jstride** [comment]
@fluppie do you know if any of these can turn on the IR Lights?

**Comment by fluppie** [comment]
Only _set_led_r_ and _set_led_b_ make the front led red or blue.

**Comment by mcchas** [comment]
@jstride you can turn on and off the IR led and filter with gpio62 (LED) and gpio78 (filter).


E.g:

echo 1 > /sys/class/gpio/gpio62/value
