### ISSUE TITLE
Rotate only for HomeKit?

### ISSUE THREAD

**Issue by mats-newborn** [mcchas/g2h-camera-mods#13]
Is it possible to get a version of this that only rotates the camera, for HomeKit users who want to mount upside down but don't want to use the Aqara app at all?
In a way that could just be easily cloned to an SD without any other changes or requirements (telnet, rtsp, etc)

Also curious if you've seen any way to disable the mic (without messing with the hardware) for cameras that could be mounted in sensitive areas? (facing out of window in bedroom or bathroom) 
In @oneminc issue with IR light, the firmware shows in the Audio section, In-Mute = 0.
Also in @fluppie issue, there seems to be a mic command of some sort. 

Just curious, appreciate your work on this.

**Comment by mcchas** [comment]
Not sure about disabling the mic - considering it is linux you should be able to just manipulate the /dev device to disable it, or a at worst you could remove the mic from the PCB.

This version does disable Aqara functions. You can modify the script to select the options you want - changing the rotation is not in there now but you can use `sed` and `md5sum` to achieve this.
