### ISSUE TITLE
Factory reset

### ISSUE THREAD

**Issue by johndoewashere2** [mcchas/g2h-camera-mods#15]
Firstly great work by the way! 

You've mentioned that there's A/B images stored in the SPI flash, is there a way to trigger a restoration of the image by any chance as neither holding the reset pin for 5-seconds nor pressing the top button 10-times consecutively does a proper "factory" reset to remove all modifications. 

Both reset process above appears to only remove HomeKit pairing data and Wi-Fi configuration only.

**Comment by mcchas** [comment]
I have found the reset button does not do an image restore - it just replaces a few files. The flash is split into two 16mb filesystems but I have not seen where the copy is done with a factory reset - this might just be used for OTA firmware upgrades. I will update the readme - but let me know if you need any files to help restore your device.

**Comment by ads1230** [comment]
> I have found the reset button does not do an image restore - it just replaces a few files. The flash is split into two 16mb filesystems but I have not seen where the copy is done with a factory reset - this might just be used for OTA firmware upgrades. I will update the readme - but let me know if you need any files to help restore your device.

Is there a way to reset the device? One of mine has some corrupt files and won't boot properly.

**Comment by mcchas** [comment]
Have you tried the factory reset procedure using the button near the SD card?
Depending on the level of brokenness you may be able to manually recover using the serial console. If that doesn't work and uboot is not an option you can always re-image the SPI flash.

**Comment by ads1230** [comment]
> Have you tried the factory reset procedure using the button near the SD card?
> Depending on the level of brokenness you may be able to manually recover using the serial console. If that doesn't work and uboot is not an option you can always re-image the SPI flash.

Would re-imaging involve cracking the device open and wiring up? No too confident with that.
