### ISSUE TITLE
no entry point, no way in

### ISSUE THREAD

**Issue by BreitiDE** [mcchas/g2h-camera-mods#19]
hey, had a look onto the boot up log, but can't find the hostname command not found entry. What do I need to do to get the hostname changed or to trigger this the rename of the host ?

I am on the version 2.2.1 and 2.1.x before also do not work ...

r Stefan

**Comment by kenhuang** [comment]
You can downgrade with these steps: https://github.com/mcchas/g2h-camera-mods/issues/10#issuecomment-848882150

**Comment by mcchas** [comment]
The hostname command was executed on boot from a new camera (without any config changes & on the firmware versions I tested) - so they may have patched this in the newer version. If you are seeing the boot logs you could possibly still log in using the serial console. The root password (if it has not changed) was discovered by another user and was shared somewhere in these GH issues.
