### ISSUE TITLE
Enabling RTSP is not working

### ISSUE THREAD

**Issue by Aleksey-Ivanov** [mcchas/g2h-camera-mods#21]
Hi @mcchas !
Could you help me?
I have downloaded your file 'hostname' on sdcard in G2H. After that I opened terminal and executed the command 'netstat -anl'. But I can't see any process is listening on port 554. What am I doing wrong?

![image](https://user-images.githubusercontent.com/4525799/127978288-f5c74b3f-69aa-4b8d-ad56-6fd4428fc4ff.png)

**Comment by mcchas** [comment]
@Aleksey-Ivanov which version of the firmware are you using?

**Comment by Aleksey-Ivanov** [comment]
2.2.1_0001.0515 This is version firmware from the app aqara home

**Comment by Aleksey-Ivanov** [comment]
@mcchas What do you think about this issue?

**Comment by mcchas** [comment]
Have you tried the most recent script? 

To enable RTSP, the hexdump/sed command just replaces the string 'miio_task' with 'rtsp_task' in a specific location in the camera file. Unfortunately when xiaomi makes updates to their firmware these bytes all shift either up or down slightly and that can break the hexdump/sed command - as it can't find the right 'miio_task' to replace. If you have tried the most recent hostname script and it doesn't work I can help work through updating the script

**Comment by Aleksey-Ivanov** [comment]
Yes, I've tried using the hostname of the latest version. It will be great if you have a chance to help me.
As I understand correctly, after this enabling RTSP, I shouldn't update via aqara home, right?

**Comment by Aleksey-Ivanov** [comment]
Could you help me, with this issue?

**Comment by mcchas** [comment]
If you can share your camera binary file I can update the sed command

**Comment by Aleksey-Ivanov** [comment]
Sure, can you explain how I to get this binary file?

**Comment by mcchas** [comment]
You could use static compiled binaries for arm7 (https://github.com/therealsaumil/static-arm-bins) but a sure fire way would be to use an SD card to copy the file /local/app.tar.zx to /sdcard.

`cp /local/app.tar.zx /sdcard/`

**Comment by agrigoriev** [comment]
Hi, Guys! Did it work?

**Comment by Aleksey-Ivanov** [comment]
@mcchas I've been updated /etc/tar_app.sh and reboot. But i can't find 554 port.
![image](https://user-images.githubusercontent.com/4525799/132351487-5d74cca5-3ab8-4fd1-a71b-f5197c994e6f.png)

Where I can find log file?

**Comment by Aleksey-Ivanov** [comment]
@mcchas How I can do full factory reset for G2H? I pressed and hold the button near 10 seconds. But it is not work.

**Comment by mcchas** [comment]
@Aleksey-Ivanov it should reset if you follow the manufacturers instructions- from memory it will sound a spoken acknowledgment of 'device reset' or similar, possibly in Chinese. 

Other than that another user in these issues was able to reset theirs by restoring some files to undo the changes the script makes. It's a unique issue you have, and the script is not 100% plug and play, but it sounds like you need some Linux  assistance to debug the running of this script, unless your camera has some strange firmware version- but that seems unlikely. The script simply patches the binary that runs the camera software, if that happened successfully RTSP should start.

**Comment by Aleksey-Ivanov** [comment]
@mcchas Thanks for your time and your helps!
@agrigoriev I've gone it!) I had to reset and re-executed  the system with your hostname file.

Maybe you know how I can get the stream video from G2H via rtsp in the VLC player?

**Comment by mcchas** [comment]
@Aleksey-Ivanov that's great! You can use rtsp://<ipaddress/14 in VLC, other paths with other numbers are also available for different resolutions (check the readme).

**Comment by mouth4war** [comment]
@Aleksey-Ivanov I have the same firmware version camera. How did you get wifi working once you reset? Did you use aqara app or homekit or miio app? I tried resetting again and still doesn't work with a FAT32 formatted 64GB card. My camera doesn't connect to homekit or to aqara app. RTSP also not working.
