### ISSUE TITLE
deleted tar_app.sh, can this be solved?

### ISSUE THREAD

**Issue by gielie** [mcchas/g2h-camera-mods#25]
Hi,
I needed to do a factory reset and dit like #22 but by accident I deleted the tar_app.sh and now it won't boot.
Is there a way to restore this?

I can still telnet into the device, so if someone can post the file here I can copy it for the sd card back.

**Comment by mcchas** [comment]
@gielie the original contents of this file are lines 54-62 of the hostname script.

**Comment by gielie** [comment]
So I just have to create a file with that content?

`#!/bin/sh
cd /local
chmod 777 *
mkdir /tmp/out
if [ -f "app.tar.xz" ]; then
        tar -xJf app.tar.xz -C /tmp/out
fi `

**Comment by mcchas** [comment]
Yes
