### ISSUE TITLE
thank you!! Telnet was successfully opened.

### ISSUE THREAD

**Issue by 1043717432** [mcchas/g2h-camera-mods#3]
telnet is open!

Next, how to use VLC media player to connect RSTP?

What is the full address of RSTP?

**Comment by PMKA** [comment]
Would love to know this too

**Comment by mcchas** [comment]
If the patched version of `/tmp/out/camera` is running - it should be. You can then access RSTP at different resolutions and with and without audio on rtsp paths /10 to /15:

rtsp://<ip address>/10
rtsp://<ip address>/11
rtsp://<ip address>/12
rtsp://<ip address>/13
rtsp://<ip address>/14
rtsp://<ip address>/15
