### ISSUE TITLE
G2H does not start

### ISSUE THREAD

**Issue by geldelo** [mcchas/g2h-camera-mods#30]
Hello. Foolishly deleted the /tmp/out/ folder and the /etc/normal.xml file. The yellow indicator is now on all the time, it does not appear on the network. What can I do?

**Comment by mcchas** [comment]
It happens. I'd think restoring normal.xml should do trick as the /tmp/out folder is untarred on startup.

normal.xml:
```
<monitor>
        <process name="/local/bin/property_service">
                <arg desc="loglevel option">-i</arg>
                <arg desc="loglevel 0">/etc/build.prop</arg>
                <arg desc="data path option">-p</arg>
                <arg desc="data path">/mnt/config/prop.dat</arg>
        </process>
        <process name="/tmp/out/mosquitto">
                <arg desc="foreground run"></arg>
        </process>
        <process name="/tmp/out/ha_agent">
                <arg desc="foreground run"></arg>
        </process>
        <process name="/tmp/out/proxy_server">
                <arg desc="foreground run">-D</arg>
        </process>
        <process name="/tmp/out/camera">
                <arg desc="bring up by monitor">-M</arg>
        </process>
        <process name="/tmp/out/ha_master">
                <arg desc="bring up by monitor">-a</arg>
                <arg desc="bring up by monitor">/lib/libha_auto.so </arg>
                <arg desc="bring up by monitor">-G</arg>
                <arg desc="bring up by monitor">/mnt/config</arg>
        </process>
        <process name="/tmp/out/zigbee_agent">
        <arg desc="bring up by monitor">-f</arg>
        <arg desc="bring up by monitor">/etc/zigbeeAgent.conf</arg>
        </process>
        <process name="/tmp/out/ha_driven">
        <arg desc="bring up by monitor">-d</arg>
        <arg desc="bring up by monitor">/mnt/config/ha_driven</arg>
        </process>
</monitor>
```

**Comment by geldelo** [comment]
![IMG_4858](https://user-images.githubusercontent.com/81517950/141954789-f9094c57-a4f9-414e-af05-cbd82bcae0a3.jpg)

I soldered the pins to the correct connectors and connected to the Uart device.

When connected to a device via Putty, I used 38400.8n1.

But Putty won't connect. I do not know what to do. Help me please.

**Comment by mcchas** [comment]
Have you tried other bitrates? It's more likely to be 115200. I usually test by swapping tx and rx as it's easy to get them around the wrong way.

**Comment by geldelo** [comment]
Thx, i connected. But can't etner any command.
On connect error:

'/dev/stdin' -> '/proc/self/fd/0'
[RCS]: /etc/init.d/S90app
Can't find upgrade file
mDNSResponder: mDNSResponder (Engineering Build) (May 27 2019 12:17:34) starting
mDNSResponder: mDNS_AddDNSServer: Lock not held! mDNS_busy (0) mDNS_reentrancy ( 0)
mDNSResponder: mDNSPlatformSourceAddrForDest: connect 1.1.1.1 failed errno 101 ( Network is unreachable)
[RCS]: /etc/init.d/S91telnetd
19700101 03:00:34.124 ERROR monitor 115: get RootElement fail
19700101 03:00:34.125 ERROR monitor 315: parser_processlist[/etc/normal.xml] fail

**Comment by mcchas** [comment]
That is interesting. The getty on the serial port is usually started from inittab - check your tx connection and ground wiring, you might need to hit a few keys during boot to get a response on the console but would be good to confirm if there are any issues there before trying anything else.
