### ISSUE TITLE
How do I change WiFi settings via Telnet?

### ISSUE THREAD

**Issue by TheStigh** [mcchas/g2h-camera-mods#31]
I've tried to change SSID/PWD both on `/mnt/config/wifi.config` and `/mnt/config/wpa_supplicant.conf`

Still, it doesn't change access point, continues to connect to the old one...

**Comment by mcchas** [comment]
Try changing this file `/mnt/config/miio/wifi.conf`

**Comment by TheStigh** [comment]
> Try changing this file `/mnt/config/miio/wifi.conf`

I am not kidding, I did try that earlier - now it worked! Thanks @mcchas   :)
