### ISSUE TITLE
How can I do firmware update to a specific firmware?

### ISSUE THREAD

**Issue by TheStigh** [mcchas/g2h-camera-mods#32]
Hi,

I want 2.1.1_001.0515 as this works with the mod.
I got the OTA file of this firmware.

App suggest 2.2.0_001.0515, but I assume the mod doesn't work on this version.

@mcchas Any suggestions ?

**Comment by mcchas** [comment]
If you update you might need to modify the script as the hex search and replace slightly changes when the file changes. If you want to upgrade you could update the script or just avoid the update.
