### ISSUE TITLE
Disable IR

### ISSUE THREAD

**Issue by nielspeen** [mcchas/g2h-camera-mods#41]
I use one of my G2H's behind glass. For this reason I need to disable IR. Is there a way to do it without restoring the Aqara app?

**Comment by nielspeen** [comment]
Found my answer here: https://github.com/mcchas/g2h-camera-mods/issues/12#issuecomment-876464602

**Comment by TheStigh** [comment]
Hi Niels, does your IR stay off after issuing the `echo 1 > /sys/class/gpio/gpio62/value` ?
