### ISSUE TITLE
Help with image flip

### ISSUE THREAD

**Issue by ads1230** [mcchas/g2h-camera-mods#5]
Hey, thank you for figuring this all out!

I am a bit lost enabling the image to flip - do you add a command to "hostname" or is there a way through telnet?

Also, is there a way to enable the timestamp?

[edit]
Ok figured it out

Connect via Telnet

`vi /mnt/config/flash_config.ini`

under [video] highlight 0 value for flip -> press `r` on your keyboard and then `3` to swap the value to 3

if you want to enable the timestamp change OSD to `1`

Scroll to the bottom, press `i` on the keyboard and delete the line with the checksum

press `esc`, then type `:wq`

generate a new checksum using `md5sum /mnt/config/flash_config.ini`

Open the file again: `vi /mnt/config/flash_config.ini`
At the bottom press `i` on the keyboard and add a new line checksum = your MD5HASH

------

On another note: if you edit the language to English in /mnt/config/factory_config.ini it remains after a factory reset.

I wonder if there is a way to swap the CN G2H to EU like someone has done for the Hub: https://kaspa.rs/xiaomi-aqara-hub-cn-on-european-server/ -> this would possibly permanently change the firmwares to the European version.

[edit 2]
To swap to the EU servers you need to edit mentions of `lumi.camera.gwagl02` to `lumi.camera.gwag03`

`cd ../`
`vi /mnt/config/miio/device.conf`
`vi /mnt/config/hostapd.conf` 
`vi etc/build.prop`

**Comment by ads1230** [comment]
Ok figured it out

Connect via Telnet

`vi /mnt/config/flash_config.ini`

under [video] highlight 0 value for flip -> press `r` on the keypad and then 3 to swap it to 3

if you want to enable the timestamp change OSD to 1

Scroll to the bottom, press `i` on the keyboard and delete the line with the checksum

press esc and then type `:wq`

generate a new checksum using `md5sum /mnt/config/flash_config.ini`

Open the file again -> `vi /mnt/config/flash_config.ini`
At the bottom press `i` on the keyboard and add a new line checksum = your MD5HASH

------

On another note: if you edit the language to English in /mnt/config/factory_config.ini it remains after a factory reset.

**Comment by Kronos-117** [comment]
Has anyone had any luck with the image flip?  Followed the steps above but the flip value just reverts back to 0.
