### ISSUE TITLE
homekit_ntp

### ISSUE THREAD

**Issue by ads1230** [mcchas/g2h-camera-mods#8]
Hey,

Do you have a bit more info on the `homekit_ntp` command?

After adding `127.0.0.1 cm.iotcplatform.com gm.iotcplatform.com aiot-coap-test.aqara.cn` to hosts the time stamp reset itself to 1970.

`homekit_ntp au.pool.ntp.org` doesn't seem to fix this, when I try to run it manually via telnet it just hangs.

**Comment by mcchas** [comment]
As soon as I run that command the system time is updated for me. Make sure you have DNS configured before running it, else it won't resolve the host name. You may want to change the server name to match your region too.

**Comment by ads1230** [comment]
Thanks, I think something corrupted when I upgraded to 2.1.1 permissions wise. 

Works on my other G2H!

———
On another note, there’s a web server inbuilt to busybox. 
https://openwrt.org/docs/guide-user/services/webserver/http.httpd

I wonder if there’s a way to make a settings page for image flip, lens correction etc
